# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=90)),
                ('denumire', models.CharField(max_length=90)),
                ('categorie', models.CharField(max_length=90)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howmanyleft.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judet', models.CharField(max_length=30)),
                ('bucati', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='judet_bucati',
            field=models.ManyToManyField(to='howmanyleft.Region'),
        ),
    ]
